---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog Posts
  create: documents
  match: "**/*"
- type: heading
  label: Content
- type: document
  path: content/home.md
  label: Home page
- type: document
  path: content/site.json
  label: Site Settings
upload_dir: content/uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:-:year:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
