---
label: Site Settings
hide_body: true
fields:
- type: text
  name: name
  label: Name
  config:
    required: true
- name: profile_pic
  type: file
  config:
    maxSize: 64
  label: Profile Pic
  description: The profile picture.
- name: site_tagline
  type: text
  config:
    required: true
  label: Site Tagline
  description: The tagline for the site. Appears in the profile area.
- type: text
  name: description
  label: Site Description
  description: The site description. Appears in SEO.
  config:
    required: false
- name: site_theme
  type: color
  label: Site Theme
  config:
    required: true
    color_format: Hex
  description: The site theme.
  default: "#CB4848"
- type: text
  name: twitter
  label: Twitter Username
  description: The username to use for Twitter. <em>Only the username</em>.
  config:
    required: true
- type: text
  name: instagram
  label: Instagram Username
  description: The username to use for Instagram. <em>Only for instagram</em>.
  config:
    required: true
- type: text
  name: medium
  label: Medium Username
  description: The username to use for Medium. <em>Only the username</em>.
  config:
    required: true
- type: text
  name: email
  label: Email
  description: The email to use for the 'say hi' section.
- name: linkedin_username
  type: text
  config:
    required: true
  label: LinkedIn Username
  description: Your LinkedIn username. Only the username, not the URL.
- name: github
  type: text
  config:
    required: true
  label: Github Username
  description: The username of your GitHub account. <em>Just the username</em>.
pages:
- content/site.json
